# Generated by Django 3.1 on 2021-04-25 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('genre', models.TextField()),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='FilmWorkPerson',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('job', models.TextField()),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.filmwork')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.person')),
            ],
            options={
                'db_table': 'film_work_person',
            },
        ),
        migrations.CreateModel(
            name='FilmWorkGenre',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.filmwork')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movies.genre')),
            ],
            options={
                'db_table': 'film_work_genre',
            },
        ),
    ]
