# Generated by Django 3.1 on 2021-04-25 09:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210425_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmWorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип кинопроизведения',
                'verbose_name_plural': 'типы кинопроизведений',
            },
        ),
        migrations.AlterField(
            model_name='filmworkperson',
            name='job',
            field=models.CharField(choices=[('actor', 'актёр'), ('director', 'режиссёр'), ('writer', 'сценарист')], max_length=32, verbose_name='должность'),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='film_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.filmworktype'),
        ),
    ]
