# Generated by Django 3.1 on 2021-04-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210425_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'человек', 'verbose_name_plural': 'люди'},
        ),
        migrations.AddField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(through='movies.FilmWorkPerson', to='movies.Person'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='film_type',
            field=models.CharField(blank=True, choices=[('tv_show', 'шоу'), ('movie', 'фильм'), ('series', 'сериал')], max_length=255, null=True, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=255, verbose_name='жанр'),
        ),
        migrations.DeleteModel(
            name='FilmWorkType',
        ),
    ]
