# Generated by Django 3.1 on 2021-04-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210425_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='film_rating',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
