# Generated by Django 3.2 on 2021-04-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210426_2129'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['title'], name='film_work_title_3625e7_idx'),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(fields=['creation_date'], name='film_work_creatio_02a6ad_idx'),
        ),
        migrations.AddIndex(
            model_name='filmworkgenre',
            index=models.Index(fields=['film_work', 'genre'], name='film_work_g_film_wo_261627_idx'),
        ),
        migrations.AddIndex(
            model_name='filmworkperson',
            index=models.Index(fields=['film_work', 'person'], name='film_work_p_film_wo_619d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='genre',
            index=models.Index(fields=['genre'], name='genre_genre_ace6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='person_name_b6df79_idx'),
        ),
    ]
