# Generated by Django 3.2.2 on 2021-05-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='film_rating',
            field=models.CharField(blank=True, default='', help_text='suitability for different age audience', max_length=32, verbose_name='возрастной рейтинг'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='film_type',
            field=models.CharField(blank=True, choices=[('tv_show', 'шоу'), ('movie', 'фильм'), ('series', 'сериал')], default='', max_length=32, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
    ]
