# Generated by Django 3.2.2 on 2021-05-26 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210511_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmwork',
            name='indexed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), verbose_name='дата индексации в ElasticSearch'),
        ),
    ]
