# Generated by Django 3.2.3 on 2021-06-05 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_filmwork_indexed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='indexed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), editable=False, verbose_name='дата индексации в ElasticSearch'),
        ),
        migrations.AddField(
            model_name='person',
            name='indexed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), editable=False, verbose_name='дата индексации в ElasticSearch'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='indexed_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), editable=False, verbose_name='дата индексации в ElasticSearch'),
        ),
    ]
